"""initial_schema

Revision ID: 662118d57511
Revises: 
Create Date: 2026-06-24 08:58:08.322975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662118d57511'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyses_raw_file_id'), 'analyses', ['raw_file_id'], unique=False)
    op.create_foreign_key(None, 'analyses', 'raw_files', ['raw_file_id'], ['id'])
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'analyses', ['analysis_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_index(op.f('ix_analyses_raw_file_id'), table_name='analyses')
    # ### end Alembic commands ###
