"""add_content_hash_to_raw_files

Revision ID: bc2993dcbbae
Revises: c4tch_up_m1ss1ng
Create Date: 2026-06-25 21:25:05.958044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2993dcbbae'
down_revision: Union[str, None] = 'c4tch_up_m1ss1ng'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_files', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # 创建复合索引（去重查询用）
    op.create_index('ix_raw_files_user_content_hash', 'raw_files', ['user_id', 'content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_files_user_content_hash', table_name='raw_files')
    op.drop_column('raw_files', 'content_hash')
    # ### end Alembic commands ###
